name: CI

on:
  push:
    branches: [main, stg]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: staging
        type: choice
        options: [staging, production]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: mohamedmagdy122/reusable-frontend-ci/.github/workflows/reusable-frontend-ci.yml@main
    with:
      node-version: '22'
      run-tests: true
      image-name: ecommerce-ui
    secrets: inherit
